window.noname_package={
	character:{
		sst_standard:'大乱桌斗',
		sst_extra:'乱斗EX',
		sst_sp:'乱斗SP',
		sst_legacy:'乱斗LE'
	},
	card:{
		sst_standard:'大乱桌斗',
		sst_extra:'乱斗EX',
		sst_sp:'乱斗明星',
		sst_land:'乱斗地图',
		standard:'标准',
		extra:'军争',
		sp:'忠胆英杰',
		guozhan:'国战',
		zhulu:'逐鹿天下',
		yingbian:'应变篇',
		yongjian:'用间篇',
		zhenfa:'阵法',
		yunchou:'运筹帷幄',
		huanlekapai:'欢乐卡牌'
	},
	play:{
		boss:'诸神降临',
		cardpile:'牌堆补充',
		wuxing:'五行生克',
		coin:'富甲天下'
	},
	mode:{
		super_smash_tabletop:'大乱桌斗',
		identity:'身份',
		th_mougong:'谋攻',
		guozhan:'国战',
		versus:'对决',
		connect:'联机',
		huanhuazhizhan:'幻化',
		doudizhu:'斗地主',
		brawl:'乱斗'
	},
	submode:{
		identity:{
			normal:'身份模式',
			zhong:'忠胆英杰',
			purple:'3v3v2'
		},
		guozhan:{
			normal:'国战模式',
			mingjiang:'明将国战'
		},
		versus:{
			four:'四人对抗',
			three:'统率三军',
			two:'欢乐成双',
			siguo:'四国争霸',
			standard:'自由对决'
		}
	},
	background:{
		standard_bg:'标准',
		battlefield_bg:'战场',
		final_destination_bg:'终点',
		smash_bg:'乱斗'
	},
	music:{
		//music_battlefield:'战场',
		music_final_destination:'终点',
		music_master_hand:'大师',
		music_crazy_hand:'疯狂',
		music_master_hand_crazy_hand:'左右',
		music_galeem:'吉拉',
		music_dharkon:'达兹',
		music_galeem_dharkon:'光暗'
	},
	font:{
		sarasa:"黑体",
		LXGWWenKai:'楷体'
	},
	theme:{
		woodden:'木纹',
		music:'音乐',
		simple:'简约'
	}
};
