window.noname_update={
	version:'1.9.116.6',
	update:'1.9.116.0',
	changeLog:[
		'更新排位赛',
	],
	files:[

	    'character/daba.js',
	    'character/liaoyuan.js',
		'game/game.js',
		'game/config.js',
		'game/package.js',
		'game/source.js',
		'game/asset.js',
		'image/splash/paiwei.jpg',
		'mode/paiwei.js'
	]
};
